#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// clear the data log so we start at row 0 each time
	datalogClear();

	// while the robot has not reached the end of the barcode, move forward at the designated speed
	while(getMotorEncoder(leftMotor) < 5300){
		setMotorSpeed(rightMotor, 50);
		setMotorSpeed(leftMotor, 50);

		// while the robot is moving forward, and is on top of the barcode. record the color sensor values into the datalog
		while(getMotorEncoder(rightMotor) > 600 && getMotorEncoder(rightMotor) < 5300){
				datalogDataGroupStart();
				datalogAddValue(0, (getColorReflected(colorSensor)));
				datalogDataGroupEnd();
		}

	}

	// once the robot has reached the end of the barcode, stop moving
	setMotorSpeed(rightMotor, 0);
	setMotorSpeed(leftMotor, 0);


}
